### ISSUE TITLE
`return_cellID` for `motif_enrichment_knn` and `motif_enrichment_dist`

### ISSUE THREAD

**Issue by keller-mark** [ShaokunAn/Spatial-Query#4]
Analogous to how the `return_cellID` flag works for `find_patterns_rand` and `find_patterns_grid`, would it be possible to implement a `return_cellID` option for `motif_enrichment_knn` and `motif_enrichment_dist`?

**Comment by ShaokunAn** [comment]
Yes, I updated motif_enrichment_knn/dist, now we can choose to return cell_id by setting return_cellID=True.
